# Generated by Django 5.1.3 on 2024-12-30 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='escort_images/'),
        ),
        migrations.CreateModel(
            name='EscortProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('heading', models.TextField()),
                ('country_code', models.CharField(max_length=5)),
                ('mobile_number', models.CharField(max_length=15)),
                ('bust_size', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('looks', models.CharField(max_length=50)),
                ('smoker', models.CharField(max_length=5)),
                ('sexual_orientation', models.CharField(max_length=50)),
                ('services', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='escort_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='profiles.escortprofile'),
        ),
    ]
